### ISSUE TITLE
Форма регистрации TimePad для ITGM #8

### ISSUE THREAD

**Issue by Leningradez** [Piter-United/index#30]
Как Потенциальный Участник, я хочу иметь возможность зарегистрироваться на мероприятие, чтобы получить электронный билет и посетить мероприятие в указанную дату.

Notes:
- этот код для кнопки на сайте, форма открывается в попапе;
- форма достаточно длинная, надо предусмотреть это =)

Код:

<a href="https://piter-united.timepad.ru/event/341694/" data-twf-placeholder="yes">Перейти к заказу билетов</a><script type="text/javascript" defer="defer" charset="UTF-8" data-timepad-customized="2669" data-timepad-widget-v2="event_register" src="https://timepad.ru/js/tpwf/loader/min/loader.js">
    (function(){return {"event":{"id":"341694"},"hidePreloading":true,"initialRoute":"button","buttonSettings":{"text":"Зарегистрироваться"}}; })();
</script>

**Comment by mike1pol** [comment]
@Leningradez готово
