### ISSUE TITLE
Header: добавить возможность "поделиться"

### ISSUE THREAD

**Issue by Leningradez** [Piter-United/index#37]
Как Посетитель, хочу иметь возможность поделиться информацией о мероприятии в социальных сетях, чтобы о мероприятии узнали мои друзья и коллеги.

Notes:
- Возможность поделиться в G+, Fb, Vk, Tw, LinkedIn;
- Разместить под кнопкой "Зарегистрироваться", с заголовком Поделиться: иконки...

Пожелания (можно сделать в самом конце):
- стилизовать иконки (монохром - svg), взяв иконки отсюда: http://www.flaticon.com/categories/social

**Comment by ikoolik** [comment]
При попытке шарить в соц сетях, картинки для поста подбираются не вполне релевантные (для facebook - RubyNoName, к примеру). Ок только для vk и twitter.

Хз стоит ли вытаскивать это в отдельную issue или можно впилить туточки, потому пишу тут. На ваш суд, господа.

**Comment by mike1pol** [comment]
@ikoolik ок, спасибо я посмотрю в чем может быть дело

**Comment by mike1pol** [comment]
@Leningradez проблема оказалась в размере логотипа, логотип должен быть не меньше 200х200 пикселей.
