### ISSUE TITLE
Блок "Общая программа"

### ISSUE THREAD

**Issue by Leningradez** [Piter-United/index#39]
- поправить шрифты, сделать "Open Sans", подобрать гармоничный размер и отступов;
- поменять дату в заголовке на 23 июля
- убрать это "адское" изображение часов в раскрывающихся секциях (можно взять иконку или вообще убрать картинку и все);
- блок с ссылкой на программу сообществ: поменять заголовок на "Программа мероприятия"
- блок с ссылкой на программу сообществ: поправить шрифты, сделать "Open Sans", подобрать гармоничный размер отступов;
- поменять ссылку на программу: https://docs.google.com/spreadsheets/d/1IkVe1NmC4xDiSsNh5BS2-H78diSxQWYOrgDP1OKIM8Y/edit?usp=sharing

**Comment by ikoolik** [comment]
Взял

**Comment by ikoolik** [comment]
Шрифты и отступы не трогал, видимо уже было поправлено, ибо выглядит ок.
